# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76c51bbbd9f7926c794a235f8c30bd70cd291ab7443eb1661f60dc67464f968790ebc5d554f5f74dbf0d6c4543877274cee5d0a749bdcf72622c8c225ecae9cb

test:
  secret_key_base: 1e525c0b8ab9560b2ff6b03f3076fb082f89faed3c3ccfcee6a67520746afe4dfa6e6075aff73346b989fe1c3b36cd260dafff5a53c86f756a1fbd92129f27b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
